let str= "ilovecoding";
console.log(str.slice(-2));
console.log(str.replace("love","do"));
console.log(str.slice(4,9));
console.log(str.indexOf("ec"));
console.log(str.replace("love","like"));
console.log(str.slice(7).replace("d","b"));  
let info =  ["Jatin",20,34,45];
info[2];
let fruits = ["apple","mango","strawberry"];
fruits[0] = "banana";
fruits[1] = "litchi";
fruits[10] = "papaya";
let cars = ["bmw","mercedes","pagani","audi"];
console.log(cars.push("toyota"));
console.log(cars.pop());
let months = ["january","july","march","august"];
console.log(months.shift("january"));
console.log(months.shift("july"));
console.log(months.unshift("june"));
console.log(months.unshift("july"));
let colors = ["red","blue","green","yellow"];
console.log(colors.indexOf("blue"));
console.log(colors.indexOf("red"));
console.log(colors.indexOf("pink"));
console.log(colors.includes("red"));
console.log(colors.includes("pink"));
console.log(colors.push("pink"));
console.log(colors.slice(2));
console.log(colors.pop("pink"));
console.log(colors.slice(1));
console.log(colors.slice(1,2));
console.log(colors.splice(0,1,"pink","violet"));  
let primary = ["red","yellow","blue"];
let secondary = ["orange","green","violet"];
console.log(primary.concat(secondary));
console.log(primary.concat(secondary).reverse());
let squares = [81,36,49,16,4,64,9,25];
console.log(squares.sort());
let mons = ["january","july","march","august"];
console.log(mons.splice(0,2,"july","june"));
let strr = ["c","c#","c++","javascript","sql","java","html","css"];
let arr = ["kotlin","php"];
console.log(strr.toReversed().indexOf("javascript"));
console.log(strr.concat(arr).toReversed());
console.log(strr.splice(2,0,"ruby"));
console.log(strr.push("python"));